name: $(Build.DefinitionName)-$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - main

pr: none

variables:
  - name: backendServiceConnection
    value: 'CloudDevOPSDev'
  - name: tfBackendResourceGroupName
    value: 'rg-learningclouddevops-dev'
  - name: tfBackendStorageAccountName
    value: 'stotfstatedev'
  - name: tfBackendContainerName
    value: 'cn-tfstate'
  - name: tfBackendKey
    value: 'terraform.tfstate'

pool: 
  name: Default
stages:
  - stage: Install
    jobs:
      - job: terraform_install
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

  - stage: VersionCheck
    dependsOn: [Install]
    jobs:
      - job: terraform_version_check
        steps:
          - task: PowerShell@2
            displayName: Check Terraform version
            inputs:
              targetType: 'inline'
              script: |
                terraform -v
                
  # - stage: GetHelp
  #   dependsOn: [VersionCheck]
  #   jobs:
  #     - job: terraform_help
  #       steps:
  #         - task: PowerShell@2
  #           displayName: Get help
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               terraform -h
  - stage: Validate
    dependsOn: [VersionCheck]
    jobs:
      - job: terraform_validate
        steps:
            - task: TerraformTaskV3@3
              inputs:
                provider: 'azurerm'
                command: 'validate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'

  - stage: Init
    dependsOn: [Validate]
    jobs:
      - job: terraform_init
        steps:
            - task: TerraformTaskV3@3
              displayName: Initialize terraform template
              inputs:
                provider: 'azurerm'
                command: 'init'
                backendServiceArm: $(backendServiceConnection)
                backendAzureRmResourceGroupName: $(tfBackendResourceGroupName)
                backendAzureRmStorageAccountName: $(tfBackendStorageAccountName)
                backendAzureRmContainerName: $(tfBackendContainerName)
                backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'

