name: $(Build.DefinitionName)-$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - main

pr: none
pool: 
  name: Default
stages:
  - stage: Build
    jobs:
      - job: terraform_init
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

  - stage: Plan
    dependsOn: [Build]
    jobs:
      - job: terraform_version_check
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                terraform -v | terraform -h