name: $(Build.DefinitionName)-$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - main

pr: none

variables:
  - name: backendServiceConnection
    value: 'CloudDevOPSDev'
  - name: tfBackendResourceGroupName
    value: 'rg-learningclouddevops-dev'
  - name: tfBackendStorageAccountName
    value: 'stotfstatedev'
  - name: tfBackendContainerName
    value: 'cn-tfstate'
  - name: tfBackendKey
    value: 'terraform.tfstate'

pool: 
  name: Default
stages:
  - stage: Install
    jobs:
      - job: terraform_install
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

          - task: PowerShell@2
            displayName: Check Terraform version
            inputs:
              targetType: 'inline'
              script: |
                terraform -v

  # - stage: GetHelp
  #   dependsOn: [VersionCheck]
  #   jobs:
  #     - job: terraform_help
  #       steps:
  #         - task: PowerShell@2
  #           displayName: Get help
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               terraform -h
  - stage: Init
    dependsOn: [Install]
    jobs:
      - job: terraform_init
        steps:
            - task: TerraformTaskV3@3
              displayName: Initialize terraform template
              inputs:
                provider: 'azurerm'
                command: 'init'
                backendServiceArm: $(backendServiceConnection)
                backendAzureRmResourceGroupName: $(tfBackendResourceGroupName)
                backendAzureRmStorageAccountName: $(tfBackendStorageAccountName)
                backendAzureRmContainerName: $(tfBackendContainerName)
                backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'

            - task: TerraformTaskV3@3
              displayName: Validate initialized template
              inputs:
                provider: 'azurerm'
                command: 'validate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'

  - stage: Plan
    dependsOn: [Init]
    jobs:
      - job: terraform_plan
        steps:
            - task: TerraformTaskV3@3
              displayName: Initialize terraform template
              inputs:
                provider: 'azurerm'
                command: 'init'
                backendServiceArm: $(backendServiceConnection)
                backendAzureRmResourceGroupName: $(tfBackendResourceGroupName)
                backendAzureRmStorageAccountName: $(tfBackendStorageAccountName)
                backendAzureRmContainerName: $(tfBackendContainerName)
                backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'

            - task: TerraformTaskV3@3
              displayName: Create an execution plan
              inputs:
                provider: 'azurerm'
                command: 'plan'
                commandOptions: '-input=false -out="$(System.DefaultWorkingDirectory)/module-iac/deploy.tfplan" -var-file="$(System.DefaultWorkingDirectory)/module-iac/terraform.tfvars"'
                # backendServiceArm: $(backendServiceConnection)
                # backendAzureRmResourceGroupName: $(tfBackendResourceGroupName)
                # backendAzureRmStorageAccountName: $(tfBackendStorageAccountName)
                # backendAzureRmContainerName: $(tfBackendContainerName)
                # backendAzureRmKey: 'terraform.tfstate'
                workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'
                environmentServiceNameAzureRM: $(backendServiceConnection)
            

  # - stage: Validate
  #   dependsOn: [Init]
  #   jobs:
  #     - job: terraform_validate
  #       steps:
  #           - task: TerraformTaskV3@3
  #             inputs:
  #               provider: 'azurerm'
  #               command: 'validate'
  #               workingDirectory: '$(System.DefaultWorkingDirectory)/module-iac/'