name: $(Build.DefinitionName)-$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - main

pr: none
pool: 
  name: Default
stages:
  - stage: InstallTF
    jobs:
      - job: terraform_init
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

  - stage: VersionCheck
    dependsOn: [InstallTF]
    jobs:
      - job: terraform_version_check
        steps:
          - task: PowerShell@2
            displayName: Check Terraform version and get help
            inputs:
              targetType: 'inline'
              script: |
                terraform -v
                
  - stage: GetHelp
    dependsOn: [VersionCheck]
    jobs:
      - job: terraform_version_check
        steps:
          - task: PowerShell@2
            displayName: Check Terraform version and get help
            inputs:
              targetType: 'inline'
              script: |
                terraform -h