resource_group_name = "learntfrg"
location = "westeurope"
tag = "dev"
storage_account_name = "learntfsto"
storage_container_name = "cn-tfstate"
# app_service_plan = "learntfasp"
# func_app_name = "learntf-func-dev"