resource_group_name = "learntfrgweu"
location = "westeurope"
tag = "dev"
storage_account_name = "learntfsto"
storage_container_name = "learntfcontainer"
app_service_plan = "learntfasp"
func_app_name = "learntf-func-dev"